### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by joshsmith**
Minor improvements to the README.

### CODE REVIEW

**Comment by joshsmith** [comment]
Unrelated thought, but I wonder if `ember-cli-draggable-shim` is a more conventional name?

**Comment by timrourke** [comment]
@JoshSmith the name of this is fairly verbose. However, I wanted to avoid confusion with [`ember-draggable`](https://www.npmjs.com/package/ember-draggable), which is already a thing.

**Comment by timrourke** [comment]
@tsov I'm interested in your thoughts here. Could the name of this package be made to be more clear?

**Comment by joshsmith** [comment]
@timrourke certainly understand the desire, though `ember-draggable` hasn't been updated in over 2 years from its `0.0.1` release and has 32 downloads in the last month. `ember-cli-draggable-shim` (still verbose) or even just `ember-cli-draggable` seems okay. I might also consider reaching out to @wireframe to see if he'll release the `npm` package name since it corresponds to `draggable` much better.

**Comment by joshsmith** [comment]
I do think `ember-draggable-shim` may make the most sense, though.

**Comment by tsov** [comment]
@timrourke thanks for reaching out! I think something like `ember-cli-draggable` or `ember-cli-draggable-shim` could work 👍

**Pull request merged**
